@domain = http://localhost:5129

GET {{domain}}/games

###
GET {{domain}}/games/2

###
POST {{domain}}/games
Content-Type: application/json

{
  "name": "Gran Turismo 7",
  "genreId": 4,
  "price": 69.99,
  "releaseDate": "2022-03-04"
}

###
PUT {{domain}}/games/2
Content-Type: application/json

{
  "name": "God of War Ragnarök",
  "genreId": 1,
  "price": 59.99,
  "releaseDate": "2022-11-09"
}

###
DELETE {{domain}}/games/2
Content-Type: application/json

###
GET {{domain}}/genres